### PR TITLE
Fix `altı`, `altın`, break `altında`

### PR DESCRIPTION
**Pull request by cmantas**

### CODE REVIEW

**Comment by cmantas** [comment]
More precisely, `altında` was already falsely stemmed to `alt`.
The correct stem is `altı`.
Now it is falsely stemmed to `altın`.
Previously `altı` was falsely stemmed to `al`, now it is correctly kept `altı`.
Neither before this commit, nor after does the stem of `altında` match the stem of `altı` as it should

**Comment by muatik** [comment]
Do the correct roots depend on the contexts in which they are used? For example; `altinda` should be differently stemmed in the following sentences:

1) "alma masanin altinda" (masanin altinda=under the table) stem=alti
2) "altinda bu yil iyi getiri var" (altinda, here it refers to `gold`) stem=altin

is the aim here, in this project, to find the shortest root/stem or to try to find correct stem in the context?

**Comment by greenonion** [comment]
@muatik hello, thanks for your input! At the moment the stemmer works on a word by word basis, i.e. it ignores context. We are aware of the limitations of the approach, however at the moment it works well enough for our use case. We might look into it sometime in the future, but it is not in our immediate plans.

**Comment by muatik** [comment]
hello! Yeap, that's reasonable. 👍

**Comment by greenonion** [comment]
LGTM

**Pull request merged**
